### ISSUE TITLE
Unwrap transforms RingChannel into OverflowingChannel partially

### ISSUE THREAD

**Issue by tyranron** [eapache/channels#26]
Let's assume that I always need only the last written value into channel whenever I read from it. For this I use the following `RingChannel`.
```go
ring := channels.NewRingChannel(1)
```

It work as intended, except I receive `interface{}` all the time. But I need more type safety, that's why I'll create the type channel and `Unwrap()` into it:

```
ch := make(chan int)
channels.Unwrap(ring.Out(), ch)
```

What happens now:

1. Assume that no one reads from `ch`.
2. Write happens into `ring.In()`, `value1` is placed inside `ring`.
3. `value1` is read inside `Unwrap()` [here](https://github.com/eapache/channels/blob/v1.1.0/channels.go#L269) and [stucks here](https://github.com/eapache/channels/blob/v1.1.0/channels.go#L274) as no one reads from `ch`.
4. Write happens into `ring.In()` again, `value2` is placed inside `ring`.
5. Write happens into `ring.In()` again, `value3` is placed inside `ring`, `value2` is discarded from `ring`.
6. Finally, someone reads from `ch` and receives `value1`, but not `value3` as expected from `channels.NewRingChannel(1)`.

So, @eapache, I understand the limitations and why this happens. Would you be so kind to point me for correct workaround here? I cannot get how to reach `channels.NewRingChannel(1)` behavior with typed channels.

**Comment by tyranron** [comment]
@eapache I think I figured it out.

I need just to write my own analogue of `Unwrap()` with "preserve last one" behaviour.

```go
	ring := channels.NewRingChannel(channels.None)
	ch := make(chan int)
	go func(received <-chan interface{}, into chan<- int) {
		var latest int
		for {
			val, open := <-received
			if !open {
				close(into)
				return
			}
			latest = val.(int)
			select {
			case into <- latest:
			default:
			}
		}
	}(ring.Out(), ch)
```

In this case the buffering happens inside `Unwrap()` analogue, so `channels.None` is used for `ring`.  
And, as we never block when writing into `ch`, we always have the latest value from `ring.Out()`.

Actually, specially for this case (buffer size `=1`) the `channels.NewRingChannel(channels.None)` may be thrown away at all and replaced with a regular Go unbuffered channel. But for higher buffer sizes this pattern may be adopted.

**Comment by tyranron** [comment]
__Update__:

Provided piece of code is wrong as `ch` reader may not read `latest` value when loop is blocked on `<-received`.

Here is correct one (I hope... 😕):

```go 
	ring := channels.NewRingChannel(channels.None)
	ch := make(chan int)
	go func(received <-chan interface{}, into chan<- int) {
		var latest int
		var send chan<- int
		for {
			select {
			case val, open := <-received:
				if !open {
					close(into)
					return
				}
				latest = val.(int)
				if send == nil {
					send = into
				}
			case send <- latest:
				// Ensure to send value only once.
				send = nil
			}
			// Yet another attempt to send value here
			// is required to ensure that value is send
			// because Go can schedule closing before sending.
			select {
			case send <- latest:
				send = nil
			default:
			}
		}
	}(ring.Out(), ch)
```

**Comment by eapache** [comment]
Glad you figured it out, yes that looks correct to me.
